package com.bmw.sale.value;

// Generated 2013-6-20 22:54:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer carid;
	private String carpic;
	private String carname;
	private float price;
	private String color;
	private String engine;
	private Integer stock;
	private Set sells = new HashSet(0);

	public Car() {
	}

	public Car(String carname, float price, String color, String engine) {
		this.carname = carname;
		this.price = price;
		this.color = color;
		this.engine = engine;
	}

	public Car(String carpic, String carname, float price, String color,
			String engine, Integer stock, Set sells) {
		this.carpic = carpic;
		this.carname = carname;
		this.price = price;
		this.color = color;
		this.engine = engine;
		this.stock = stock;
		this.sells = sells;
	}

	public Integer getCarid() {
		return this.carid;
	}

	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	public String getCarpic() {
		return this.carpic;
	}

	public void setCarpic(String carpic) {
		this.carpic = carpic;
	}

	public String getCarname() {
		return this.carname;
	}

	public void setCarname(String carname) {
		this.carname = carname;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getEngine() {
		return this.engine;
	}

	public void setEngine(String engine) {
		this.engine = engine;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Set getSells() {
		return this.sells;
	}

	public void setSells(Set sells) {
		this.sells = sells;
	}

}
