package com.bmw.sale.value;

// Generated 2013-6-20 22:54:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer clientid;
	private Sell sell;
	private String clientname;
	private String clientsex;
	private int clientage;
	private String clientphone;
	private String clientmail;
	private Set services = new HashSet(0);

	public Client() {
	}

	public Client(String clientname, String clientsex, int clientage,
			String clientphone, String clientmail) {
		this.clientname = clientname;
		this.clientsex = clientsex;
		this.clientage = clientage;
		this.clientphone = clientphone;
		this.clientmail = clientmail;
	}

	public Client(Sell sell, String clientname, String clientsex,
			int clientage, String clientphone, String clientmail, Set services) {
		this.sell = sell;
		this.clientname = clientname;
		this.clientsex = clientsex;
		this.clientage = clientage;
		this.clientphone = clientphone;
		this.clientmail = clientmail;
		this.services = services;
	}

	public Integer getClientid() {
		return this.clientid;
	}

	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	public Sell getSell() {
		return this.sell;
	}

	public void setSell(Sell sell) {
		this.sell = sell;
	}

	public String getClientname() {
		return this.clientname;
	}

	public void setClientname(String clientname) {
		this.clientname = clientname;
	}

	public String getClientsex() {
		return this.clientsex;
	}

	public void setClientsex(String clientsex) {
		this.clientsex = clientsex;
	}

	public int getClientage() {
		return this.clientage;
	}

	public void setClientage(int clientage) {
		this.clientage = clientage;
	}

	public String getClientphone() {
		return this.clientphone;
	}

	public void setClientphone(String clientphone) {
		this.clientphone = clientphone;
	}

	public String getClientmail() {
		return this.clientmail;
	}

	public void setClientmail(String clientmail) {
		this.clientmail = clientmail;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}

}
