package com.bmw.sale.value;

// Generated 2013-6-20 22:54:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String password;
	private String sex;
	private Byte age;
	private String loginname;
	private String department;
	private Set sells = new HashSet(0);

	public Employee() {
	}

	public Employee(String username, String password, String sex,
			String loginname, String department) {
		this.username = username;
		this.password = password;
		this.sex = sex;
		this.loginname = loginname;
		this.department = department;
	}

	public Employee(String username, String password, String sex, Byte age,
			String loginname, String department, Set sells) {
		this.username = username;
		this.password = password;
		this.sex = sex;
		this.age = age;
		this.loginname = loginname;
		this.department = department;
		this.sells = sells;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Byte getAge() {
		return this.age;
	}

	public void setAge(Byte age) {
		this.age = age;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public Set getSells() {
		return this.sells;
	}

	public void setSells(Set sells) {
		this.sells = sells;
	}

}
