package com.bmw.sale.value;

// Generated 2013-6-20 22:54:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sell generated by hbm2java
 */
public class Sell implements java.io.Serializable {

	private int engineid;
	private Car car;
	private Employee employee;
	private Date selldate;
	private Set clients = new HashSet(0);

	public Sell() {
	}

	public Sell(int engineid, Date selldate) {
		this.engineid = engineid;
		this.selldate = selldate;
	}

	public Sell(int engineid, Car car, Employee employee, Date selldate,
			Set clients) {
		this.engineid = engineid;
		this.car = car;
		this.employee = employee;
		this.selldate = selldate;
		this.clients = clients;
	}

	public int getEngineid() {
		return this.engineid;
	}

	public void setEngineid(int engineid) {
		this.engineid = engineid;
	}

	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getSelldate() {
		return this.selldate;
	}

	public void setSelldate(Date selldate) {
		this.selldate = selldate;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
